name: Build Electron App

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - v*.*.*

jobs:
  release:
    name: build and release electron app

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3
        with:
          node-version: 14

      - name: npm install
        run: |
          npm install

      # build app for win
      - name: build windows app
        if: matrix.os == 'windows-latest'
        run: |
          npm run electron:build-win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # build app for mac
      - name: build mac app
        if: matrix.os == 'macos-latest'
        run: |
          npm run electron:build-mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # build app for linux
      - name: build linux app
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run electron:build-linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
